# fly.toml app configuration file generated for notes-app-backend-test on 2023-05-15T22:20:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notes-app-backend-test"
primary_region = "lhr"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
